language: python
python:
  - "3.6"
cache: pip
install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - python test.py
after_success:
  - coverage report
  - coveralls
